# Generated by Django 4.2 on 2025-05-13 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                (
                    "texte",
                    models.TextField(
                        help_text="Description narrative de l'étape du jeu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JoueurState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("faim", models.IntegerField(default=100)),
                ("energie", models.IntegerField(default=100)),
                ("moral", models.IntegerField(default=100)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "scenario_actuel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="survie_api.scenario",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.CharField(max_length=255)),
                ("delta_faim", models.IntegerField(default=0)),
                ("delta_energie", models.IntegerField(default=0)),
                ("delta_moral", models.IntegerField(default=0)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choix",
                        to="survie_api.scenario",
                    ),
                ),
                (
                    "scenario_suivant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="choix_precedent",
                        to="survie_api.scenario",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="joueurstate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("session_id__isnull", False),
                    _connector="OR",
                ),
                name="joueur_identification",
            ),
        ),
    ]
